services:
  wg-easy:
    build:
      dockerfile: ./Dockerfile
    command: npm run serve
    volumes:
      - ./src/:/app/
      # - ./data/:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # - PASSWORD=p
      - WG_HOST=192.168.1.123
      - LANG=en
      - PASSWORD_HASH=$$2a$$12$$PodiQr5BAZNYe8UoHJ9q5e53bM3AkDxMy44CbP0BP8qXIng4BJPeW # 1234
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
